# config-repo/analysis-service.yml
spring:
  application:
    name: analysis-service

  datasource:
    url: jdbc:mysql://s4.java21.net:13306/aiot02_team2
    username: aiot02_team2
    password: m/NWS@3y-8)UZ2Zo

server:
  port: 10261
