spring:
  application:
    name: analysis-service

  datasource:
    url: jdbc:mysql://s4.java21.net:13306/aiot02_team2
    username: aiot02_team2
    password: m/NWS@3y-8)UZ2Zo

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 10261

gemini:
  api:
    key: AIzaSyDICxc4TI8A6rddEPA_lrGhWpoBdska-gE

logging:
  level:
    org.springframework.web.client.RestTemplate: DEBUG
