eureka:
  client:
    service-url:
      defaultZone: http://localhost:10252/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
    
logging:
  file:
    path: ./logs
  level:
    root: debug

management:
  endpoints:
    web:
      exposure:
        include: health,info,refresh,env,configprops,conditions
  endpoint:
    refresh:
      enabled: true

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://s4.java21.net:13306/aiot02_team2
    username: aiot02_team2
    password: m/NWS@3y-8)UZ2Zo
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none
