eureka:
  client:
    service-url:
      defaultZone: http://<CONFIG_SERVER_HOST>:10267/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true

logging:
  pattern:
    console: "%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n"
  file:
    path: ./logs
