eureka:
  client:
    service-url:
      defaultZone: http://localhost:10252/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true

logging:
  file:
    path: ./logs

management:
  endpoints:
    web:
      exposure:
        include: health,info,refresh,env,configprops
  endpoint:
    refresh:
      enabled: true
