# config-repo/eureka-service.yml
spring:
  application:
    name: eureka-service

server:
  port: 10252

eureka:
  client:
    register-with-eureka: false   
    fetch-registry: false         
  server:
    wait-time-in-ms-when-sync-empty: 0  

management:
  endpoints:
    web:
      exposure:
        include: health,info,env 
