# config-repo/gateway-service.yml
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      default-filters: DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials

server:
  port: 10251

jwt:
  secret: |
    -----BEGIN PUBLIC KEY-----
    MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAk51nWMvBVwGlg5hoolq2
    J0zZgbmGVnF6ZkzQlosz2bZQU8I21LU0Y2GW78W+3l/edBY8G8yAEy3AyubILNLA
    TSMB+kc3ZH+tTjycLIcyJiETR+dwGkzUcYKP++JsKNdEsevlkCtZ+QMTf5oblv57
    FaZxAqsCKFr5/iRwckP0KxVyyBPM0WXypqiFUb5xHKzXAs7+1uOIft2xW1pzV8xD
    SC63zDakepY+LFPijufVgA28PRR5M/i4g5M/LcXXT6ZznIOxIq52bTvDgAur32ce
    71eVC7ZesHzW5o/bwN1BcnZ4uIuaUNEUSyEpUKOsZUOWHOSqMGAwuImD9PT/h6kS
    oQIDAQAB
    -----END PUBLIC KEY-----
