# config-repo/gateway-service.yml
spring:
  application:
    name: gateway-service

server:
  port: 10251

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      globalcors:
        corsConfigurations:
          "[/**]":
            allowedOriginPatterns: "*"
            allowedMethods: GET,POST,PUT,DELETE
            allowedHeaders: "*"
            allowCredentials: true

jwt:
  secret: |
    -----BEGIN PUBLIC KEY-----
    MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAk51nWMv...
    -----END PUBLIC KEY-----
