# config-repo/gateway-service.yml
spring:
  application:
    name: gateway-service

server:
  port: 10251

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      globalcors:
        corsConfigurations:
          [/api/v1/token/**]:
            allowedOriginPatterns: "*"
            allowedMethods: "GET,POST,PUT,DELETE"
            allowedHeaders: "*"
            allowCredentials: true
            maxAge: 3600
          [/api/v1/members/**]:
            allowedOriginPatterns: "*"
            allowedMethods: "GET,POST,PUT,DELETE"
            allowedHeaders: "*"
            allowCredentials: true
            maxAge: 3600
          [/api/v1/attendances/**]:
            allowedOriginPatterns: "*"
            allowedMethods: "GET,POST,PUT,DELETE"
            allowedHeaders: "*"
            allowCredentials: true
            maxAge: 3600
          [/api/v1/bookings/**]:
            allowedOriginPatterns: "*"
            allowedMethods: "GET,POST,PUT,DELETE"
            allowedHeaders: "*"
            allowCredentials: true
            maxAge: 3600
           [/api/v1/meeting-rooms/**]:
            allowedOriginPatterns: "*"
            allowedMethods: "GET,POST,PUT,DELETE"
            allowedHeaders: "*"
            allowCredentials: true
            maxAge: 3600
          [/api/v1/chat/**]:
            allowedOriginPatterns: "http://localhost:10253"
            allowedMethods: "GET,POST,PUT,DELETE"
            allowedHeaders: "*"
            allowCredentials: true
            maxAge: 3600
        add-to-simple-url-handler-mapping: true
      default-filters: DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials

jwt:
  secret: |
    -----BEGIN PUBLIC KEY-----MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAk51nWMvBVwGlg5hoolq2J0zZgbmGVnF6ZkzQlosz2bZQU8I21LU0Y2GW78W+3l/edBY8G8yAEy3AyubILNLATSMB+kc3ZH+tTjycLIcyJiETR+dwGkzUcYKP++JsKNdEsevlkCtZ+QMTf5oblv57FaZxAqsCKFr5/iRwckP0KxVyyBPM0WXypqiFUb5xHKzXAs7+1uOIft2xW1pzV8xDSC63zDakepY+LFPijufVgA28PRR5M/i4g5M/LcXXT6ZznIOxIq52bTvDgAur32ce71eVC7ZesHzW5o/bwN1BcnZ4uIuaUNEUSyEpUKOsZUOWHOSqMGAwuImD9PT/h6kSoQIDAQAB-----END PUBLIC KEY-----
