# config-repo/iot-service.yml
spring:
  application:
    name: iot-service

server:
  port: 10266

spring:
  data:
    redis:
      host: localhost
      port: 6379

rule-engine-service:
  url: http://localhost:10263
