# config-repo/member-service.yml
spring:
  application:
    name: member-service
  datasource:
    url: jdbc:mysql://s4.java21.net:13306/aiot02_team2
    username: aiot02_team2
    password: m/NWS@3y-8)UZ2Zo

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none

server:
  port: 10255

eureka:
  instance:
    hostname: localhost
