# config-repo/notify-service.yml
spring:
  application:
    name: notify-service

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://s4.java21.net:13306/aiot02_team2
    username: aiot02_team2
    password: m/NWS@3y-8)UZ2Zo
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none

  rabbitmq:
    host: s4.java21.net
    port: 5672
    username: admin
    password: nhnacademy123!

  mail:
    host: smtp.gmail.com
    port: 587
    protocol: smtp
    username: knagsw5990@gmail.com
    password: lckzixzmryvliiba
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    default-encoding: UTF-8
    debug: true

server:
  port: 10260

email:
  queue: email-queue

