# config-repo/work-entry-service.yml
spring:
  application:
    name: work-entry-service

server:
  port: 10256

spring:
  config:
    import: optional:file:.env[.properties]

spring:
  mail:
    host: smtp.gmail.com
    port: 465
    protocol: smtp
    properties:
      mail:
        debug: true
        smtp:
          connectiontimeout: 5000
          ssl:
            enable: true
          auth: true
  mail:
    default-encoding: UTF-8

member:
  service:
    url: http://localhost:10255

spring:
  datasource:
    url: jdbc:mysql://s4.java21.net:13306/aiot02_team2
    username: aiot02_team2
    password: m/NWS@3y-8)UZ2Zo

influxdb:
  url: https://influx.aiot2.live
  token: RmaabELI9VpYPRu4nt_xBZX5l3Gv5lx8XnR4mVZnqep4Ya3eYrfpLUk4Y4dYE4J0mlcFHFPLUCKh8a4jq_lMNw==
  org: aiot2-team2-coffee
  bucket: coffee-mqtt

admin:
  email: kim5472678@gmail.com
