name: Trigger Config Server Rebuild

on:
  push:
    branches: [ main ]

jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: 호출용 GitHub API 패키지 설치
        run: sudo apt-get update && sudo apt-get install -y jq curl

      - name: Send repository_dispatch to config-server via curl
        env:
          API_TOKEN: ${{ secrets.PAT_FOR_CONFIG_SERVER }}
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $API_TOKEN" \
            https://api.github.com/repos/Pangyo-Coffee-Legends/config-server/dispatches \
            -d '{"event_type":"rebuild"}'
